<?php
$z[0]=Array("articletype","\r\n                {\r\n                @me=\"<span class='articletype arc-type-v'>¹Ûµã</span>\";\r\n                }\r\n                [field:articletype",53,234);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",261,276);
$z[2]=Array("litpic","",318,333);
$z[3]=Array("arcurl","",447,462);
$z[4]=Array("fulltitle","",480,498);
$z[5]=Array("writer","",605,620);
$z[6]=Array("pubdate","",659,705);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",747,767);
$z[8]=Array("id","",793,826);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",976,991);
$z[10]=Array("id","",1045,1056);

?>