<?php
$z[0]=Array("articletype","\r\n        switch(@me)\r\n        case \"industryNews\":\r\n            @me = \"产业新闻\";\r\n            break;\r\n        case \"view\":\r\n            @me = \"观点\";\r\n            break;\r\n        case \"deepInsight\":\r\n            @me = \"深度测评\";\r\n            break;\r\n        case \"etc\":\r\n            @me = \"其他\";\r\n            break;\r\n        default:\r\n            @me = \"最新文章\";\r\n            break;\r\n        ",0,450);
$z[0][4]['runphp']="yes";
$z[1]=Array("articletype","",544,564);
$z[2]=Array("arcurl","",598,613);
$z[3]=Array("litpic","",655,670);
$z[4]=Array("arcurl","",784,799);
$z[5]=Array("fulltitle","",817,835);
$z[6]=Array("writer","",942,957);
$z[7]=Array("pubdate","",996,1042);
$z[7][4]['function']="GetDateTimeMK(@me)";
$z[8]=Array("description","",1084,1104);
$z[9]=Array("id","",1130,1163);
$z[9][4]['function']="GetTags(@me)";
$z[10]=Array("arcurl","",1313,1328);
$z[11]=Array("id","",1382,1393);

?>