<?php
$z[0]=Array("articletype","\r\n        switch(@me)\r\n        {\r\n        case \"industryNews\":\r\n            @me = \"<span class='articletype arc-type-in'>产业新闻</span>\";\r\n            break;\r\n        case \"view\":\r\n            @me = \"<span class='articletype arc-type-v'>观点</span>\";\r\n            break;\r\n        case \"deepInsight\":\r\n            @me = \"<span class='articletype arc-type-di'>深度测评</span>\";\r\n            break;\r\n        case \"etc\":\r\n            @me = \"<span class='articletype arc-type-etc'>其他</span>\";\r\n            break;\r\n        default:\r\n            @me = \"<span class='articletype arc-type-latest'>最新文章</span>\";\r\n            break;\r\n        }\r\n        ",0,701);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",777,792);
$z[2]=Array("litpic","",834,849);
$z[3]=Array("arcurl","",963,978);
$z[4]=Array("fulltitle","",996,1014);
$z[5]=Array("writer","",1121,1136);
$z[6]=Array("pubdate","",1175,1221);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",1263,1283);
$z[8]=Array("id","",1309,1342);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",1492,1507);
$z[10]=Array("id","",1561,1572);

?>