<?php
$z[0]=Array("arcurl","",130,145);
$z[1]=Array("litpic","",187,202);
$z[2]=Array("arcurl","",316,331);
$z[3]=Array("fulltitle","",349,367);
$z[4]=Array("writer","",474,489);
$z[5]=Array("pubdate","",528,574);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",616,636);
$z[7]=Array("id","",662,695);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("arcurl","",845,860);
$z[9]=Array("id","",914,925);

?>