<?php
$z[0]=Array("articletype","\r\n                @me=\"<span class='articletype arc-type-di'>…Ó∂»≤‚∆¿</span>\";\r\n                [field:articletype",53,201);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",228,243);
$z[2]=Array("litpic","",285,300);
$z[3]=Array("arcurl","",414,429);
$z[4]=Array("fulltitle","",447,465);
$z[5]=Array("writer","",572,587);
$z[6]=Array("pubdate","",626,672);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",714,734);
$z[8]=Array("id","",760,793);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",943,958);
$z[10]=Array("id","",1012,1023);

?>