<field:tradingAccountName itemname="账户名称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:tradingAccountName>
<field:broker itemname="经纪商" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:broker>
<field:brokerLogo itemname="经纪商Logo" autofield="1" notsend="0" type="image" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:brokerLogo>
<field:regulation itemname="账户可选监管" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:regulation>
<field:brokerType itemname="交易模式" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:brokerType>
<field:software itemname="交易软件" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:software>
<field:quotationAccuracy itemname="报价精确度" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:quotationAccuracy>
<field:minDeposit itemname="最低入金数" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:minDeposit>
<field:accountCurrencies itemname="可使用的基准货币" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:accountCurrencies>
<field:marginCallLevel itemname="追缴保证金水平" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:marginCallLevel>
<field:stopOutLevel itemname="强制平仓水平" autofield="1" notsend="0" type="float" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:stopOutLevel>
<field:maxOpeningOrders itemname="最高敞口订单数" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:maxOpeningOrders>
<field:forexMaxOpeningLots itemname="外汇最高持仓手数" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:forexMaxOpeningLots>
<field:spotmetalMaxOpeningLots itemname="贵金属最高持仓手数" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:spotmetalMaxOpeningLots>
<field:indexMaxOpeningLots itemname="指数最高持仓手数" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:indexMaxOpeningLots>
<field:commoditiesMaxOpeningLots itemname="大宗最高持仓手数" autofield="1" notsend="0" type="int" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:commoditiesMaxOpeningLots>

<field:whatever itemname="whatever" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:whatever>
