<ul>
                              <li>[field:broker_name/]</li>
                          </ul>

                      </div>
                      <p>Anchor paragraph</p>
                  </div>
              </div>
          </div>
          <script>
              $(document).ready(function(){
                  $('input').iCheck({
                      checkboxClass: 'icheckbox_square-green',
                      radioClass: 'iradio_square-green',
                      increaseArea: '20%' // optional
                  });
              });
              $("#maxlev").slider({
                  tooptip:'hide'
              });
          </script>

          <div>
          {dede:include filename="footer_index.htm"