<?php
$z[0]=Array("arcurl","",132,147);
$z[1]=Array("litpic","",189,204);
$z[2]=Array("arcurl","",318,333);
$z[3]=Array("fulltitle","",351,369);
$z[4]=Array("writer","",476,491);
$z[5]=Array("pubdate","",530,576);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",618,638);
$z[7]=Array("id","",664,697);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("arcurl","",847,862);
$z[9]=Array("id","",916,927);

?>