
<field:tradingAccountName itemname="账户名称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:tradingAccountName>

<field:broker itemname="经纪商" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:broker>

<field:regulation itemname="账户可选监管" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:regulation>
