<a href="[field:arcurl/]" class="list-item-box" title="[field:title/]">
            <dl class="list-item">
                <dt class="pic">[field:image/]</dt>
                <dd><div class="news-info">
                    <div class="news-title">[field:title/]</div>
                    <div class="news-info-bottom">
                        <span>[field:typename/]</span><span class="news-date">[field:pubdate function="MyDate('m‘¬d»’ H:s',@me)"/]</span>
                    </div>
                </div>
                </dd>
            </dl>
        </a>