<tr>
                                      <td class="cell-with-border">
                                          <div class="brokerinfo-col-1">
                                              <b>[field:broker_name/]&nbsp&nbsp&nbsp[field:broker_name_cn/]</b>
                                          </div>
                                          <div class="brokerinfo-col-1">
                                              <b>监管：</b>
                                              <a href="[field:main_license_href/]">[field:main_license/]</a>
                                          </div>
                                          <div class="brokerinfo-logo">
                                              <img src="[field:broker_logo/]" class="broker-logo"/>
                                          </div>
                                      </td>
                                      <td colspan="2" class="broker-info-col-2">
                                          <div>
                                              <b>所属国家：</b>
                                              [field:headquarter/]
                                          </div>
                                          <div>
                                              <b>成立时间：</b>
                                              [field:date_founded/]
                                          </div>
                                          <div>
                                              <b>经营模式：</b>
                                              [field:operation_mode_cn/]
                                          </div>
                                          <div>
                                              <b>入金方式：</b>
                                              [field:deposit_mode/]
                                          </div>
                                          <div>
                                              <b>出金方式：</b>
                                              [field:withdraw_mode/]
                                          </div>
                                      </td>
                                      <td broker-info-col-3>
                                          <div>
                                              <div>
                                                  <b>&#x20AC/$：</b>
                                                  [field:eurusd/]
                                              </div>
                                              <div>
                                                  <b>Au ：</b>
                                                  [field:gold/]
                                              </div>
                                          </div>
                                      </td>
                                      <td broker-info-col-4>
                                          <div>
                                              <button type="submit">
                                                  立即开户
                                              </button>
                                          </div>
                                      </td>
                                  </tr>