<?php
$z[0]=Array("articletype","\r\n        switch(@me)\r\n        {\r\n        case \"industryNews\":\r\n            @me = \"产业新闻\";\r\n            break;\r\n        case \"view\":\r\n            @me = \"观点\";\r\n            break;\r\n        case \"deepInsight\":\r\n            @me = \"深度测评\";\r\n            break;\r\n        case \"etc\":\r\n            @me = \"其他\";\r\n            break;\r\n        default:\r\n            @me = \"最新文章\";\r\n            break;\r\n        }\r\n        ",0,472);
$z[0][4]['runphp']="yes";
$z[1]=Array("articletype","",566,586);
$z[2]=Array("arcurl","",620,635);
$z[3]=Array("litpic","",677,692);
$z[4]=Array("arcurl","",806,821);
$z[5]=Array("fulltitle","",839,857);
$z[6]=Array("writer","",964,979);
$z[7]=Array("pubdate","",1018,1064);
$z[7][4]['function']="GetDateTimeMK(@me)";
$z[8]=Array("description","",1106,1126);
$z[9]=Array("id","",1152,1185);
$z[9][4]['function']="GetTags(@me)";
$z[10]=Array("arcurl","",1335,1350);
$z[11]=Array("id","",1404,1415);

?>