<?php
$z[0]=Array("articletype","\r\n        switch(@me)\r\n        {\r\n        case \"industryNews\":\r\n            @me = \"<span class='articletype arc-type-in'>产业新闻</span>\";\r\n            break;\r\n        case \"view\":\r\n            @me = \"<span class='articletype arc-type-v'>观点</span>\";\r\n            break;\r\n        case \"deepInsight\":\r\n            @me = \"<span class='articletype arc-type-di'>深度测评</span>\";\r\n            break;\r\n        case \"etc\":\r\n            @me = \"<span class='article arc-type-etc'>其他</span>\";\r\n            break;\r\n        default:\r\n            @me = \"<span class='articletype arc-type-latest'>最新文章</span>\";\r\n            break;\r\n        }\r\n        ",0,697);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",773,788);
$z[2]=Array("litpic","",830,845);
$z[3]=Array("arcurl","",959,974);
$z[4]=Array("fulltitle","",992,1010);
$z[5]=Array("writer","",1117,1132);
$z[6]=Array("pubdate","",1171,1217);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",1259,1279);
$z[8]=Array("id","",1305,1338);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",1488,1503);
$z[10]=Array("id","",1557,1568);

?>