<?php
$z[0]=Array("articletype","\r\n                @me=\"<span class='articletype arc-type-v'>¹Ûµã</span>\";\r\n                [field:articletype",53,196);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",223,238);
$z[2]=Array("litpic","",280,295);
$z[3]=Array("arcurl","",409,424);
$z[4]=Array("fulltitle","",442,460);
$z[5]=Array("writer","",567,582);
$z[6]=Array("pubdate","",621,667);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",709,729);
$z[8]=Array("id","",755,788);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",938,953);
$z[10]=Array("id","",1007,1018);

?>