<?php
$z[0]=Array("articletype","\r\n        switch(@me)\r\n        {\r\n        case \"industryNews\":\r\n            @me = \"<span class=\"article-type-in\">产业新闻</span>\";\r\n            break;\r\n        case \"view\":\r\n            @me = \"观点\";\r\n            break;\r\n        case \"deepInsight\":\r\n            @me = \"深度测评\";\r\n            break;\r\n        case \"etc\":\r\n            @me = \"其他\";\r\n            break;\r\n        default:\r\n            @me = \"最新文章\";\r\n            break;\r\n        }\r\n        ",0,509);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",585,600);
$z[2]=Array("litpic","",642,657);
$z[3]=Array("arcurl","",771,786);
$z[4]=Array("fulltitle","",804,822);
$z[5]=Array("writer","",929,944);
$z[6]=Array("pubdate","",983,1029);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",1071,1091);
$z[8]=Array("id","",1117,1150);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",1300,1315);
$z[10]=Array("id","",1369,1380);

?>