<?php
$z[0]=Array("articletype","\r\n                switch(@me)\r\n                {\r\n                case \"industryNews\":\r\n                @me = \"<span class='articletype arc-type-in'>产业新闻</span>\";\r\n                break;\r\n                case \"view\":\r\n                @me = \"<span class='articletype arc-type-v'>观点</span>\";\r\n                break;\r\n                case \"deepInsight\":\r\n                @me = \"<span class='articletype arc-type-di'>深度测评</span>\";\r\n                break;\r\n                case \"etc\":\r\n                @me = \"<span class='articletype arc-type-etc'>其他</span>\";\r\n                break;\r\n                default:\r\n                @me = \"<span class='articletype arc-type-latest'>最新文章</span>\";\r\n                break;\r\n                }\r\n                ",53,866);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",893,908);
$z[2]=Array("litpic","",950,965);
$z[3]=Array("arcurl","",1079,1094);
$z[4]=Array("fulltitle","",1112,1130);
$z[5]=Array("writer","",1237,1252);
$z[6]=Array("pubdate","",1291,1337);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",1379,1399);
$z[8]=Array("id","",1425,1458);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",1608,1623);
$z[10]=Array("id","",1677,1688);

?>