<?php
$z[0]=Array("articletype","\r\n                {\r\n                @me=\"<span class='articletype arc-type-in'>产业新闻</span>\";\r\n                }\r\n                [field:articletype",53,239);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",266,281);
$z[2]=Array("litpic","",323,338);
$z[3]=Array("arcurl","",452,467);
$z[4]=Array("fulltitle","",485,503);
$z[5]=Array("writer","",610,625);
$z[6]=Array("pubdate","",664,710);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",752,772);
$z[8]=Array("id","",798,831);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",981,996);
$z[10]=Array("id","",1050,1061);

?>