<?php
$z[0]=Array("arcurl","",128,143);
$z[1]=Array("litpic","",185,200);
$z[2]=Array("arcurl","",314,329);
$z[3]=Array("fulltitle","",347,365);
$z[4]=Array("writer","",472,487);
$z[5]=Array("pubdate","",526,572);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",614,634);
$z[7]=Array("id","",660,693);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("arcurl","",843,858);
$z[9]=Array("id","",916,927);

?>