<tr>
                                      <td>
                                          <div>
                                              [field:broker_name/]
                                          </div>
                                          <div>
                                              [field:main_license/]
                                          </div>
                                      </td>
                                      <td colspan="4">
                                           <div>
                                               [field:headquarter/]
                                           </div>
                                          <div>
                                              [field:broker_logo/]
                                          </div>
                                      </td>
                                  </tr>