<?php
$z[0]=Array("arcurl","",137,152);
$z[1]=Array("litpic","",194,209);
$z[2]=Array("arcurl","",323,338);
$z[3]=Array("fulltitle","",356,374);
$z[4]=Array("writer","",481,496);
$z[5]=Array("pubdate","",535,581);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",623,643);
$z[7]=Array("id","",669,702);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("arcurl","",852,867);
$z[9]=Array("id","",921,932);

?>