<?php
$z[0]=Array("arcurl","",62,77);
$z[1]=Array("litpic","",119,134);
$z[2]=Array("articletype","\r\n                switch(@me)\r\n                {\r\n                case \"industryNews\":\r\n                @me = \"<span class='articletype arc-type-in'>产业新闻</span>\";\r\n                break;\r\n                case \"view\":\r\n                @me = \"<span class='articletype arc-type-v'>观点</span>\";\r\n                break;\r\n                case \"deepInsight\":\r\n                @me = \"<span class='articletype arc-type-di'>深度测评</span>\";\r\n                break;\r\n                case \"etc\":\r\n                @me = \"<span class='articletype arc-type-etc'>其他</span>\";\r\n                break;\r\n                default:\r\n                @me = \"<span class='articletype arc-type-latest'>最新文章</span>\";\r\n                break;\r\n                }\r\n                ",184,997);
$z[2][4]['runphp']="yes";
$z[3]=Array("arcurl","",1080,1095);
$z[4]=Array("fulltitle","",1113,1131);
$z[5]=Array("writer","",1238,1253);
$z[6]=Array("pubdate","",1292,1338);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",1380,1400);
$z[8]=Array("id","",1426,1459);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",1609,1624);
$z[10]=Array("id","",1678,1689);

?>