<?php
$z[0]=Array("body","	\n",0,152);
$z[0][4]['itemname']="文章内容";
$z[0][4]['autofield']="0";
$z[0][4]['notsend']="0";
$z[0][4]['type']="htmltext";
$z[0][4]['isnull']="true";
$z[0][4]['islist']="1";
$z[0][4]['default']="";
$z[0][4]['maxlength']="";
$z[0][4]['page']="split";
$z[1]=Array("articletype","\r\n",155,344);
$z[1][4]['itemname']="文章类型";
$z[1][4]['autofield']="1";
$z[1][4]['notsend']="0";
$z[1][4]['type']="select";
$z[1][4]['isnull']="true";
$z[1][4]['islist']="1";
$z[1][4]['default']="产业新闻,观点,深度测评,其他";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";

?>