<?php
$z[0]=Array("broker_name","",198,218);
$z[1]=Array("broker_name_cn","",233,256);
$z[2]=Array("main_license_href","",502,528);
$z[3]=Array("main_license","",530,551);
$z[4]=Array("broker_logo","",736,756);
$z[5]=Array("headquarter","",1118,1138);
$z[6]=Array("date_founded","",1350,1371);
$z[7]=Array("operation_mode_cn","",1583,1609);
$z[8]=Array("deposit_mode","",1821,1842);
$z[9]=Array("withdraw_mode","",2054,2076);
$z[10]=Array("eurusd","",2639,2654);
$z[11]=Array("gold","",2877,2890);

?>