<?php
$z[0]=Array("articletype","\r\n                @me=\"<span class='articletype arc-type-etc'>ÆäËû</span>\";\r\n                [field:articletype",53,198);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",225,240);
$z[2]=Array("litpic","",282,297);
$z[3]=Array("arcurl","",411,426);
$z[4]=Array("fulltitle","",444,462);
$z[5]=Array("writer","",569,584);
$z[6]=Array("pubdate","",623,669);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",711,731);
$z[8]=Array("id","",757,790);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",940,955);
$z[10]=Array("id","",1009,1020);

?>