<?php
$z[0]=Array("articletype","\r\n                @me=\"<span class='articletype arc-type-etc'>ÆäËû</span>\";\r\n                [field:articletype",53,198);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",226,241);
$z[2]=Array("litpic","",283,298);
$z[3]=Array("arcurl","",412,427);
$z[4]=Array("fulltitle","",445,463);
$z[5]=Array("writer","",570,585);
$z[6]=Array("pubdate","",624,670);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",712,732);
$z[8]=Array("id","",758,791);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",941,956);
$z[10]=Array("id","",1010,1021);

?>