<?php
$z[0]=Array("articletype","",80,100);
$z[1]=Array("arcurl","",134,149);
$z[2]=Array("litpic","",191,206);
$z[3]=Array("arcurl","",320,335);
$z[4]=Array("fulltitle","",353,371);
$z[5]=Array("writer","",478,493);
$z[6]=Array("pubdate","",532,578);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",620,640);
$z[8]=Array("id","",666,699);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",849,864);
$z[10]=Array("id","",918,929);

?>