<?php
$z[0]=Array("articletype","",53,73);
$z[1]=Array("arcurl","",101,116);
$z[2]=Array("litpic","",158,173);
$z[3]=Array("arcurl","",287,302);
$z[4]=Array("fulltitle","",320,338);
$z[5]=Array("writer","",445,460);
$z[6]=Array("pubdate","",499,545);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",587,607);
$z[8]=Array("id","",633,666);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",816,831);
$z[10]=Array("id","",885,896);

?>