<tr>
                                      <td>
                                          <div>
                                              [field:broker_name/]
                                          </div>
                                          <div>
                                              <img src="[field:broker_logo/]" width="100" height="33"/>
                                          </div>
                                      </td>
                                      <td colspan="4">
                                          <div>
                                              [field:main_license/]
                                          </div>
                                          <div>
                                              <a href="[field:main_license_href/]"><img src="[field:main_license_logo/]" width="75" height="25"/></a>
                                          </div>
                                      </td>
                                  </tr>