<?php
$z[0]=Array("articletype","\r\n                @me=\"<span class='articletype arc-type-v'>¹Ûµã</span>\";\r\n                [field:articletype",53,196);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",224,239);
$z[2]=Array("litpic","",281,296);
$z[3]=Array("arcurl","",410,425);
$z[4]=Array("fulltitle","",443,461);
$z[5]=Array("writer","",568,583);
$z[6]=Array("pubdate","",622,668);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",710,730);
$z[8]=Array("id","",756,789);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",939,954);
$z[10]=Array("id","",1008,1019);

?>