<?php
$z[0]=Array("articletype","\r\n                {\r\n                @me=\"<span class='articletype arc-type-etc'>ÆäËû</span>\";\r\n                }\r\n                [field:articletype",53,236);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",263,278);
$z[2]=Array("litpic","",320,335);
$z[3]=Array("arcurl","",449,464);
$z[4]=Array("fulltitle","",482,500);
$z[5]=Array("writer","",607,622);
$z[6]=Array("pubdate","",661,707);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",749,769);
$z[8]=Array("id","",795,828);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",978,993);
$z[10]=Array("id","",1047,1058);

?>