<?php
$z[0]=Array("broker_name","",198,218);
$z[1]=Array("broker_name_cn","",233,256);
$z[2]=Array("main_license_href","",502,528);
$z[3]=Array("main_license","",530,551);
$z[4]=Array("broker_logo","",736,756);
$z[5]=Array("headquarter","",1092,1112);
$z[6]=Array("date_founded","",1324,1345);
$z[7]=Array("operation_mode_cn","",1557,1583);
$z[8]=Array("deposit_mode","",1795,1816);
$z[9]=Array("withdraw_mode","",2028,2050);
$z[10]=Array("eurusd","",2350,2365);
$z[11]=Array("gold","",2573,2586);

?>