<?php
$z[0]=Array("articletype","\r\n                switch(@me)\r\n                {\r\n                case \"industryNews\":\r\n                @me = \"<span class='articletype arc-type-in'>产业新闻</span>\";\r\n                break;\r\n                case \"view\":\r\n                @me = \"<span class='articletype arc-type-v'>观点</span>\";\r\n                break;\r\n                case \"deepInsight\":\r\n                @me = \"<span class='articletype arc-type-di'>深度测评</span>\";\r\n                break;\r\n                case \"etc\":\r\n                @me = \"<span class='articletype arc-type-etc'>其他</span>\";\r\n                break;\r\n                default:\r\n                @me = \"<span class='articletype arc-type-latest'>最新文章</span>\";\r\n                break;\r\n                }\r\n                ",53,882);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",909,924);
$z[2]=Array("litpic","",966,981);
$z[3]=Array("arcurl","",1095,1110);
$z[4]=Array("fulltitle","",1128,1146);
$z[5]=Array("writer","",1253,1268);
$z[6]=Array("pubdate","",1307,1353);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",1395,1415);
$z[8]=Array("id","",1441,1474);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",1624,1639);
$z[10]=Array("id","",1693,1704);

?>