
<field:tradingAccountName itemname="账户名称" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:tradingAccountName>

<field:broker itemname="经纪商" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:broker>

<field:regulation itemname="账户可选监管" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:regulation>

<field:brokerType itemname="交易模式" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:brokerType>

<field:software itemname="交易软件" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:software>

<field:quotationAccuracy itemname="报价精确度" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:quotationAccuracy>

<field:minDeposit itemname="最低入金数" autofield="1" notsend="0" type="int" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:minDeposit>
