<?php
$z[0]=Array("articletype","\r\n        switch(@me)\r\n        {\r\n        case \"industryNews\":\r\n            @me = \"产业新闻\";\r\n            break;\r\n        case \"view\":\r\n            @me = \"观点\";\r\n            break;\r\n        case \"deepInsight\":\r\n            @me = \"深度测评\";\r\n            break;\r\n        case \"etc\":\r\n            @me = \"其他\";\r\n            break;\r\n        default:\r\n            @me = \"最新文章\";\r\n            break;\r\n        }\r\n        ",0,472);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",548,563);
$z[2]=Array("litpic","",605,620);
$z[3]=Array("arcurl","",734,749);
$z[4]=Array("fulltitle","",767,785);
$z[5]=Array("writer","",892,907);
$z[6]=Array("pubdate","",946,992);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",1034,1054);
$z[8]=Array("id","",1080,1113);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",1263,1278);
$z[10]=Array("id","",1332,1343);

?>