<?php
$z[0]=Array("arcurl","",133,148);
$z[1]=Array("litpic","",190,205);
$z[2]=Array("arcurl","",319,334);
$z[3]=Array("fulltitle","",352,370);
$z[4]=Array("writer","",477,492);
$z[5]=Array("pubdate","",531,577);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",619,639);
$z[7]=Array("id","",665,698);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("arcurl","",848,863);
$z[9]=Array("id","",917,928);

?>