<?php
$z[0]=Array("arcurl","",62,77);
$z[1]=Array("litpic","",119,134);
$z[2]=Array("arcurl","",248,263);
$z[3]=Array("fulltitle","",281,299);
$z[4]=Array("writer","",436,451);
$z[5]=Array("pubdate","",490,536);
$z[5][4]['function']="GetDateTimeMK(@me)";
$z[6]=Array("description","",578,598);
$z[7]=Array("id","",624,657);
$z[7][4]['function']="GetTags(@me)";
$z[8]=Array("arcurl","",807,822);
$z[9]=Array("id","",876,887);
$z[10]=Array("mid","global \$dsql;\$sql='SELECT userid FROM dede_member WHERE mid='.@me;\$spaceurl = \$dsql->GetOne(\$sql);@me=\$spaceurl['userid'];",1065,1223);
$z[10][4]['runphp']="yes";
$z[11]=Array("writer","",1241,1256);
$z[12]=Array("pubdate","",1299,1345);
$z[12][4]['function']="GetDateTimeMK(@me)";
$z[13]=Array("id","",1464,1475);
$z[14]=Array("id","",1524,1535);
$z[15]=Array("description","",1619,1639);
$z[16]=Array("id","",1665,1698);
$z[16][4]['function']="GetTags(@me)";

?>