<?php
$z[0]=Array("articletype","\r\n                @me=\"<span class='articletype arc-type-in'>产业新闻</span>\";\r\n                [field:articletype",53,201);
$z[0][4]['runphp']="yes";
$z[1]=Array("arcurl","",229,244);
$z[2]=Array("litpic","",286,301);
$z[3]=Array("arcurl","",415,430);
$z[4]=Array("fulltitle","",448,466);
$z[5]=Array("writer","",573,588);
$z[6]=Array("pubdate","",627,673);
$z[6][4]['function']="GetDateTimeMK(@me)";
$z[7]=Array("description","",715,735);
$z[8]=Array("id","",761,794);
$z[8][4]['function']="GetTags(@me)";
$z[9]=Array("arcurl","",944,959);
$z[10]=Array("id","",1013,1024);

?>