<tr>
                                      <td>
                                          <div>
                                              <b>[field:broker_name/]&nbsp&nbsp&nbsp[field:broker_name_cn/]</b>
                                          </div>
                                          <div>
                                              <a href="[field:main_license_href/]">[field:main_license/]</a>
                                          </div>
                                          <div>
                                              <img src="[field:broker_logo/]" width="100" height="33"/>
                                          </div>
                                      </td>
                                      <td colspan="4">
                                          <div>
                                              [field:main_license/]
                                          </div>
                                      </td>
                                  </tr>