<?php
$z[0]=Array("broker_name","",198,218);
$z[1]=Array("broker_name_cn","",233,256);
$z[2]=Array("main_license_href","",502,528);
$z[3]=Array("main_license","",530,551);
$z[4]=Array("broker_logo","",736,756);
$z[5]=Array("headquarters","",1092,1113);
$z[6]=Array("date_founded","",1325,1346);
$z[7]=Array("operation_mode_cn","",1558,1584);
$z[8]=Array("deposit_mode","",1796,1817);
$z[9]=Array("withdraw_mode","",2029,2051);
$z[10]=Array("eurusd","",2351,2366);
$z[11]=Array("gold","",2574,2587);

?>