<?php
$z[0]=Array("include","",314,349);
$z[0][4]['filename']="head.htm";
$z[1]=Array("arclist","\r\n        <a href=\"[field:arcurl/]\" class=\"list-item-box\" title=\"[field:title/]\">\r\n            <dl class=\"list-item\">\r\n                <dt class=\"pic\">[field:image/]</dt>\r\n                <dd><div class=\"news-info\">\r\n                    <div class=\"news-title\">[field:title/]</div>\r\n                    <div class=\"news-info-bottom\">\r\n                        <span>[field:typename/]</span><span class=\"news-date\">[field:pubdate function=\"MyDate('m‘¬d»’ H:s',@me)\"/]</span>\r\n                    </div>\r\n                </div>\r\n                </dd>\r\n            </dl>\r\n        </a>\r\n        ",428,1128);
$z[1][4]['row']="15";
$z[1][4]['imgwidth']="80";
$z[1][4]['imgheight']="60";
$z[1][4]['titlelen']="60";
$z[1][4]['orderby']="id";
$z[1][4]['orderway']="DESC";
$z[2]=Array("include","",1150,1187);
$z[2][4]['filename']="footer.htm";

?>